// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdumvflrlpmlfsmwampz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkdW12ZmxybHBtbGZzbXdhbXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODk3NTgsImV4cCI6MjA1NjU2NTc1OH0.aULv2HFiDs5-Kd4wYBzJ1QEfksBlzzYB2JpvYN5UCME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);